version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db.mssql
    volumes:
      - db-data:/var/opt/mssql
      - ./env/restore:/restore
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}

  oipa:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - ./env/logs:/logs
    ports:
      - 9080:9080
      - 9443:9443
      - 7777:7777
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=sa
      - DB_PASSWORD=${DB_PASSWORD}
      - IVS_DB_NAME=${IVS_DB_NAME}

  palette:
    build:
      context: .
      dockerfile: Dockerfile.palette
    entrypoint: /bin/bash
    tty: true
    links:
      - db
      - oipa
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/snd"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - IVS_DB_NAME=${IVS_DB_NAME}
      - DB_USER=sa
      - DB_PASSWORD=${DB_PASSWORD}
      - DISPLAY=unix$DISPLAY

  query:
    build:
      context: .
      dockerfile: Dockerfile.query
    entrypoint: /bin/bash
    tty: true
    links:
      - db
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=unix$DISPLAY

  eclipse:
    build:
      context: .
      dockerfile: Dockerfile.eclipse
    entrypoint: /bin/bash
    tty: true
    links:
      - db
      - oipa
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./env/eclipse/workspace:/home/developer/eclipse-workspace
      - ./env/eclipse/prefs:/home/developer/.eclipse
      - ./env/eclipse/m2:/home/developer/.m2
      - ./env/eclipse/git:/home/developer/git
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=unix$DISPLAY


volumes:
  db-data:
