version: "3"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db.mssql
    volumes:
      - db-data:/var/opt/mssql
      - ./env/restore:/restore
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SQLServerPass1

  oipa:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - 9080:9080
      - 9443:9443
      - 7777:7777
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=sa
      - DB_PASSWORD=SQLServerPass1

volumes:
  db-data:
