version: "3.3"

services:
  rdp:
    build:
      context: .
      dockerfile: Dockerfile.rdp
    networks:
      - oipa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/src/v10
      - ssh:/home/ubuntu/.ssh
    ports:
      - 3389:3389

volumes:
  ssh:

networks:
  oipa:
    external: true
