version: "3.3"

services:
  rdp:
    build:
      context: ./rdp
      dockerfile: Dockerfile
    networks:
      - oipa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home/ubuntu/src/v10
      - ssh:/home/ubuntu/.ssh
      - scratch:/home/ubuntu/scratch
    ports:
      - 3389:3389

volumes:
  ssh:
  scratch:

networks:
  oipa:
    external: true
