version: "3.3"

services:
  query:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - oipa
    volumes:
      - scratch:/root/scratch
      - ssh:/root/ssh

volumes:
  scratch:
  ssh:

networks:
  oipa:
    external: true
