version: "3.3"

services:
  x11:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - oipa
    volumes:
      - ssh:/root/.ssh

volumes:
  ssh:

networks:
  oipa:
    external: true
