version: "3.3"

services:
  eclipse:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - oipa
    volumes:
      - eclipse_workspace:/home/developer/eclipse-workspace
      - eclipse_prefs:/home/developer/.eclipse
      - m2:/home/developer/.m2
      - git:/home/developer/git
      - scratch:/home/developer/scratch
      - ssh:/home/developer/ssh

volumes:
  eclipse_workspace:
  eclipse_prefs:
  m2:
  git:
  scratch:
  ssh:
  overrides:

networks:
  oipa:
    external: true
