version: "3.3"

services:
  eclipse:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - eclipse_workspace:/home/developer/eclipse-workspace
      - eclipse_prefs:/home/developer/.eclipse
      - m2:/home/developer/.m2
      - git:/home/developer/git
      - scratch:/home/developer/scratch
      - ~/.gitconfig:/home/developer/.gitconfig
      - ssh:/home/developer/.ssh
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=unix$DISPLAY
    ports:
      - 8080:8080

volumes:
  eclipse_workspace:
  eclipse_prefs:
  m2:
  git:
  scratch:
  ssh:
